### ISSUE TITLE
Server Specification

### ISSUE THREAD

**Issue by hesoyamcode** [DeepTrial/Retina-VesselNet#1]
Hi Xing ChenCong

Previously big thanks for the good code! I have questions what kind of server / compute you use to achieve the train and test result? And how long it takes?

Thanks

**Comment by DeepTrial** [comment]
Hi，
I trained it on my own laptop(msi GL62m 7rd) with one GTX 1050 2g GPU.I trained for about 2 hours and the loss vanished
