### ISSUE TITLE
Calculating Metrics within FOV

### ISSUE THREAD

**Issue by arvindmvepa** [DeepTrial/Retina-VesselNet#15]
Hi, I noticed in your algorithm you didn't calculate the metrics within the FOV of the masks provided by the DRIVE dataset. Do you know what your results will be if you used them?

**Comment by qiuxiaqing** [comment]
Yes, i have calculate the metrics within the FOV in your provided image data. The overall performance is as following.
dice coefficient : 0.824914013895
f1 score : 0.825105859784, accuracy : 0.955521674835, sensitivity : 0.824265254506, specificity : 0.974665786642  ROC_AUC: 0.978783940805, PR_AUC: 0.911825479207

**Comment by arvindmvepa** [comment]
Thanks. Can you update the code too?

**Comment by xihuanliuliu** [comment]
> Yes, i have calculate the metrics within the FOV in your provided image data. The overall performance is as following.
> dice coefficient : 0.824914013895
> f1 score : 0.825105859784, accuracy : 0.955521674835, sensitivity : 0.824265254506, specificity : 0.974665786642 ROC_AUC: 0.978783940805, PR_AUC: 0.911825479207

can you upload code?

**Comment by SIAT-liyang** [comment]
> Yes, i have calculate the metrics within the FOV in your provided image data. The overall performance is as following.
> dice coefficient : 0.824914013895
> f1 score : 0.825105859784, accuracy : 0.955521674835, sensitivity : 0.824265254506, specificity : 0.974665786642 ROC_AUC: 0.978783940805, PR_AUC: 0.911825479207

请问你能上传评估代码吗？谢谢~
