### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './experiments/VesselNet/dataset/train/groundtruth/./emanual1.tif'

### ISSUE THREAD

**Issue by ItsNala** [DeepTrial/Retina-VesselNet#19]
This message comes up when running main_training.py 

I don't understand where this error is coming from as I cannot find where we are actually looking for a file 'emanual1.tif'. 

Did someone run in the same issue?

**Comment by llmir** [comment]
same issue， so how to solve it？thx！
