### ISSUE TITLE
time

### ISSUE THREAD

**Issue by Meepozzzzz** [DeepTrial/Retina-VesselNet#2]
老哥你是中国人吧，直接中文了，我想问这么多层的网络，你用的什么配置，训练了多久，跟u-net训练时间比起来怎么样

**Comment by DeepTrial** [comment]
我是gtx1050 2g显存+i7 7700k的配置  我自己训练的时候收敛的很快，大概总共20分钟左右，和unet相比差不多

**Comment by DeepTrial** [comment]
@nocis  从这里下载  链接: https://pan.baidu.com/s/1hYd7vS2bWhIFUGgVyg98hw 密码: cvrv，然后放到DataSet文件夹下

**Comment by nocis** [comment]
非常感谢！
