### ISSUE TITLE
关于结果和参数设置的问题

### ISSUE THREAD

**Issue by CuiZhiying** [DeepTrial/Retina-VesselNet#20]
你好，非常感谢大佬提供的如此整洁的代码。但是我在复现这个结果的时候，只能在验证集上达到95%左右的结果，用的是默认的参数配置，patch_size 是96*96，我想知道我该怎样设置参数才能达到98.4%左右的结果呢？

**Comment by ahsan3803** [comment]
嗨，我在运行此代码时遇到问题，您能帮助我解决此问题吗？请分享您的电子邮件或微信ID。谢谢您的支持。

**Comment by DeepTrial** [comment]
@CuiZhiying 你好，你有遇到什么问题吗？

**Comment by DeepTrial** [comment]
@ahsan3803  你好，你遇到了什么问题？

**Comment by DeepTrial** [comment]
@CuiZhiying 这个问题我再尝试一下，感谢。

**Comment by DeepTrial** [comment]
我已经更新了代码，欢迎尝试
