### ISSUE TITLE
FCN?

### ISSUE THREAD

**Issue by xuchunyuan** [DeepTrial/Retina-VesselNet#22]
这个是基于FCN的吧？那在建模的最后为什么要reshape成（None,9216, 2）呢？为什么不直接输出图片？
既然是逐像素分类，像素的标签是在数据集中已经标好了还是在代码中标注的？代码里没看到。
训练过程划分patch是随机划分的，还是每张图片划分出500个patch？

**Comment by DeepTrial** [comment]
reshape 是为了计算loss方便。取块的过程中是同时从groundtruth和image中截取区域的，所以会有每个patch的类标，取块的时候也是随机选取，条件是patch中至少一个像素包含血管。
