### ISSUE TITLE
Test err

### ISSUE THREAD

**Issue by llmir** [DeepTrial/Retina-VesselNet#26]
Traceback (most recent call last):
  File "main_test.py", line 40, in <module>
    main_test()
  File "main_test.py", line 34, in main_test
    drawCurve(gtlist,[problist],modelName,'DRIVE',config.checkpoint)
  File "/home/mir/project/Retina-VesselNet/perception/metric/segmention_metric.py", line 209, in drawCurve
    (FPR, TPR, AUC), (Precision, Recall, MAP),IoU = process.statistics()
  File "/home/mir/project/Retina-VesselNet/perception/metric/segmention_metric.py", line 38, in statistics
    assert(len(self.groundtruth)==len(self.probgraph))
AssertionError

could anyone tell me why would this happen and how to solve it? thx a lot!

**Comment by DeepTrial** [comment]
@llmir  maybe you can check whether the num of gt images is right?

**Comment by llmir** [comment]
20 orgins and 20 gts, i haven't make any changes yet  o(╥﹏╥)o.  btw，would you mind telling me your wechat☺

**Comment by llmir** [comment]
[Info] Analyze filename... 05_test
new full images shape: 
(1, 588, 568, 1)
11445/11445 [==============================] - 6s 549us/step
N_patches_h: 109
N_patches_w: 105
N_patches_img: 11445

According to the dimension inserted, there are 1 full images (of 588x568 each)
11445 11445
using avg
(584, 565, 1)
[INFO] Metric results...
  0%|          | 0/255 [00:00<?, ?it/s]

why 584 565? is this the reason?

**Comment by DeepTrial** [comment]
wechat id：angularlock.  Maybe that is the problem, i have not checked the code

**Comment by llmir** [comment]
all you have to do is delete the origin imgs in results, and this err solved.
