### ISSUE TITLE
希望在我的研究中使用您的代码

### ISSUE THREAD

**Issue by lauranceair** [DeepTrial/Retina-VesselNet#27]
您好，我这边之前给您主页上留的邮箱发了一封邮件，希望能使用您的代码在我的课题上面，并且如果有论文发表，我这边将会给您挂作者，不知道您这边同不同意。希望能得到您的答复。

**Comment by DeepTrial** [comment]
@lauranceair  不好意思之前没有留意到邮箱，您的要求我完全可以同意。
