### ISSUE TITLE
About config_utils.py

### ISSUE THREAD

**Issue by Purdandelion** [DeepTrial/Retina-VesselNet#3]
from bunch import Bunch 
error is No module named bunch 
I cannot find  content about bunch ,wolud you tell me how you learn this bunch,thanks

**Comment by DeepTrial** [comment]
have u tried pip install bunch?

**Comment by Purdandelion** [comment]
ok, I have finished , Your code is too powerful

**Comment by DeepTrial** [comment]
if no other problem,i will close this issue:)
