### ISSUE TITLE
hello author, I am getting this error when I run main_trian.py  ValueError: zero-size array to reduction operation maximum which has no identity

### ISSUE THREAD

**Issue by MaleehaKhan** [DeepTrial/Retina-VesselNet#34]

**Comment by xizhilanting** [comment]
你好，找到解决方案了吗？Hello, have you found a solution for this error?

**Comment by boba1234** [comment]
Hi i am getting this error too

**Comment by MaleehaKhan** [comment]
keep the original settings or try this file, hope it helps

Maleeha Khalid Khan




________________________________

**Comment by boba1234** [comment]
Thanks for the reply. i've kept the original settings without changing anything in the codes. May i ask which file are you referring to? There was no file attached.

**Comment by MaleehaKhan** [comment]
Prepare_datasets_DRIVE.py has been attached

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by boba1234** [comment]
i've sent an email to you~ can you attach the code there? Thanks alot!

**Comment by MaleehaKhan** [comment]
Hi there,
attached with this mail is the prepare_datasets_DRIVE.py file, put this file in 'retina blood vessel segmentation' and in BCDU-Net master folder put DRIVE data (the data is available online) and then run the code it will work perfectly .

Maleeha Khalid Khan




________________________________

**Comment by MaleehaKhan** [comment]
code

Maleeha Khalid Khan




________________________________

**Comment by manvirvirk** [comment]
> Hi i am getting this error too

hi i m getting same error, did you find solution to it?

**Comment by MaleehaKhan** [comment]
In step 1 generate images for val_data, then use it in 2 step could be a solution ...

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by manvirvirk** [comment]
hi i want to train this model on my own database. I have images and respective labels. Can any one help??

**Comment by DeepTrial** [comment]
hello guys， i have update the code. If you still have problems, open the issue again
