### ISSUE TITLE
Hello, may I ask if I can use pictures of other sizes for training

### ISSUE THREAD

**Issue by fubai3** [DeepTrial/Retina-VesselNet#37]
Hello, I want to use other pictures of fixed size for training. Is it ok? Is there any requirement on the ratio of height to width?Want to change the parameters there?thank youMy email is 1165269652@qq.com

**Comment by Wuyanfang5** [comment]
The author hello, is it convenient to add your WeChat consultation
My E-mail 1165269652 @qq.com

**Comment by TAEiche** [comment]
I tried to train with a new dataset and different size, it worked well. Remember to change the settings in the segmentation_configs.json file.

**Comment by Wuyanfang5** [comment]
> 我尝试使用新的数据集和不同的大小进行训练，效果很好。记住要更改segmentation_configs.json文件中的设置。

好的，谢谢，请问您训练的时候loss和准确率能到多少，我110张图训练了120epoch，两个类别。测试效果不太好，loss=0.3703，准确率百分之五十一左右，请问有什么方法可以用来改进效果，谢谢

**Comment by TAEiche** [comment]
I trained on the HRF Dataset (45 pictures) for 20 epochs, and achieved an loss~0.12 and an train/val-Accuracy of ~0.95/94.
On what data are you training?

**Comment by Wuyanfang5** [comment]
> 我在HRF数据集（45张图片）上训练了20个时间段，损失约0.12，火车/阀门精度约0.95 / 94。
> 您正在训练什么数据？

您好，我训练的是自己的数据集，想问问您标签是程序自动标注的还是labelme标注的呢，预测结果出来后如何知道血管信息的具体位置呢，谢谢

**Comment by TAEiche** [comment]
I dont know if i got you right, but you need to generate the masks and the GT-data on your own. The code wont do this for you. Sorry if this does not help you. Using google Translate...

**Comment by Wuyanfang5** [comment]
> 我不知道我是否正确，但是您需要自己生成遮罩和GT数据。代码不会为您这样做。抱歉，如果这样对您没有帮助。使用谷歌翻译...

谢谢，现在我的loss降到0.022左右了，可是分类精度依然是0.52/0.53左右，请问是不是我的标签转换问题，您制作自己 的数据集标签的时候是如何制作的呢，我的邮箱1165269652@qq.com，谢谢

**Comment by DeepTrial** [comment]
I have update the code. You can find the method  on the jupyter notebook.  if you still have the problem, open the issue again
