### ISSUE TITLE
How to test model on multiple images?

### ISSUE THREAD

**Issue by Alpheron** [DeepTrial/Retina-VesselNet#39]
Hello,
I was trying to test this model out on multiple images instead of just one and I wanted to know how that would be possible since when I currently have more than one image in the test/origin directory, the test results end up getting overwritten. Any help would be greatly appreciated.

Thanks,
Aditya

**Comment by DeepTrial** [comment]
I have update the code. You can find the method  on the jupyter notebook.  if you still have the problem, open the issue again
