### ISSUE TITLE
Pretrained model does not achieve as high AUC as stated

### ISSUE THREAD

**Issue by Ralphyan** [DeepTrial/Retina-VesselNet#4]
Hi,

I tried your pretrained model, and re-trained the model my myself, but the final AUC is only about 0.71. Can you check what caused the difference?

Thanks

**Comment by DeepTrial** [comment]
What dataset do you use? DRIVE dataset? Can you give me more detials? I will try to help you:)

**Comment by Ralphyan** [comment]
I used DRIVE dataset, downloaded  with the link in your document. Thanks a lot.

**Comment by DeepTrial** [comment]
Ok,I will try to find out the problem.

**Comment by DeepTrial** [comment]
@Ralphyan  Sorry,I find that I upload the wrong version that use a small unet network.Now I have fixed it, you can reclone it and test again.
