### ISSUE TITLE
ROC is not more than 0.5857 and PR is not more than 0.1196

### ISSUE THREAD

**Issue by shabeeh2129** [DeepTrial/Retina-VesselNet#41]
I am having an issue with the ROC curve and PR graph.  Their values are not very good. I tried predefined models as well as trained myself using the data you provided. And more the output images are not good.

Help me if I am doing anything wrong.
I am working on Colab using GPU. 
Help me how can I achieve more accuracy.

**Comment by DeepTrial** [comment]
I have update the code, if you still have the problem, open the issue again. thx
