### ISSUE TITLE
Error in visualisation module

### ISSUE THREAD

**Issue by putlurusurya** [DeepTrial/Retina-VesselNet#43]
![image](https://user-images.githubusercontent.com/43723182/122855061-438be800-d332-11eb-96a9-f3cdced94642.png)

**Comment by nanadaime** [comment]
Hello @putlurusurya ,

what did you do and got rid of this bug ?

**Comment by putlurusurya** [comment]
hey @nanadaime use the individual files provided not the entire notebook for colab. They work just fine.

**Comment by nanadaime** [comment]
Oh, okay, thanks a lot for the clarification ❤
