### ISSUE TITLE
训练自己的数据集时出现了以下问题，想请教一下。

### ISSUE THREAD

**Issue by xiewenxin** [DeepTrial/Retina-VesselNet#7]
您好，我看了你的项目，觉得非常有意思，现在想用你的模型训练自己的数据，但是在读取图片的时候出现了以下提示，想请教一下。
standerd_loader.py
  imgs[index,:,:,0]=np.asarray(orgImg[:,:,1]*0.75+orgImg[:,:,0]*0.25)

IndexError: too many indices for array

想请教一下 imgs[index,:,:,0]=np.asarray(orgImg[:,:,1]*0.75+orgImg[:,:,0]*0.25) 这段代码的目的是什么呢？

**Comment by DeepTrial** [comment]
您好！眼底RGB图片中G通道能够更好表现血管特征，这里以0.25,0.75的比例混合红色通道与绿色通道，生成血管更加明显的图片。你可以先把RGB图像的三个通道分离后显示出来，仔细体会一下
